# General Zsh configs

# Portable aliases and functions.
[ -f ~/.shrc ] && . ~/.shrc

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

autoload -U compinit
compinit
command -v jj >/dev/null && source <(jj util completion zsh)
